### ISSUE TITLE
The downloaded chat history is not stored locally 

### ISSUE THREAD

**Issue by predictron-cloud** [famedly/matrix-dart-sdk#1526]
Some matrix clients store the downloaded chat history, so that it is accessible in offline mode. For fluffy chat only last 5 messages are available in offline mode. Storing of the history can also be beneficial for performance, as there will be less queries to the server.

```[tasklist]
- [x]  The issue title and description should be explained in English language.
- [ ] Feature request is provided in story template:
- [x] Business value is clear and understood.
- [x] Every attached media (if applicable) should include a short description.
- [ ] Engineer has confirmed this feature is technically feasible.
```

**Comment by predictron-cloud** [comment]
For example: when I open room and then return back to room list and then back to room it loads once again.

**Comment by krille-chan** [comment]
Chat history is stored locally with the matrix dart sdk. If you only have the last 5 messages then you have probably received a limited_timeline flag
