### ISSUE TITLE
Flutter encrypted messages

### ISSUE THREAD

**Issue by BlackCult666** [famedly/matrix-dart-sdk#1531]
Hey, I'm making a Flutter chat app using matrix, I used the example code and all works fine, but the text of encrypted messages appears like "m.room.encrypted" and does not show the real text. 
I saw on pub.dev that to include E2EE you have to install flutter_olm and flutter_openssl_crypto, but what do i have to do after installing them? They give me a problem, when i try to run the app on Android Studio it gets stopped and gives me a long error which says that the versions of those libs are lower than Android Gradle plugin's supported ones. If i remove olm and openssl, all works perfectly, but as I said, I can't see the encrypted messages text.

**Comment by krille-chan** [comment]
This is a docs problem not a bug. To solve your Gradle problem I would suggest to take a look into the docs of the packages
