### ISSUE TITLE
Read receipts inconsistent with other sdks

### ISSUE THREAD

**Issue by Airyzz** [famedly/matrix-dart-sdk#1549]
Hi, im currently in the process of making a client with this sdk, and I noticed that the read receipts seems to be inconsistent with other clients. 

Looking at a large room, like #matrix-dev:matrix.org clients Cinny and Element are showing that the latest message is read by 14 people, wheras Fluffychat and my project are only showing significantly fewer

To reproduce, just open the same room in two clients, one using this sdk, like Fluffychat, and another not using this sdk, Element, Cinny, etc. and observe the difference in read receipts

**Comment by techno-disaster** [comment]
Probably because some clients use the main thread for receipts, while the `event.receipts` getter only gives you receipts from the global unthreaded timeline. You could try playing with `room.receiptState` to get what you want.

**Comment by Airyzz** [comment]
Thanks I'll have a look in to that. Would you expect that to still be the case for rooms which havent had any opened threads? From what I can tell this issue is still showing in such a room, but I may have to look further in to it

**Comment by Airyzz** [comment]
Was able to get it working with the main thread, thanks!
