### ISSUE TITLE
Compatibility Issue: Flutter OLM Plugin with Kotlin Gradle Plugin 1.3.50

### ISSUE THREAD

**Issue by Vinayak0-0** [famedly/matrix-dart-sdk#1555]
**Issue Description:**
I encountered a compatibility issue when trying to use the Flutter OLM plugin in my Flutter project. The error message suggests that the Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher, while the Flutter OLM plugin relies on Kotlin Gradle plugin version 1.3.50.

**Steps to Reproduce:**
1. Create a Flutter project.
2. Add the Flutter OLM plugin to the project dependencies.
3. Attempt to build the project with the current Kotlin Gradle plugin version (1.7.10).

**Expected Behavior:**
I expected the Flutter OLM plugin to work seamlessly with my Flutter project without encountering version conflicts.

**Actual Behavior:**
I encountered an error message indicating that the Kotlin Gradle plugin version is incompatible with the Flutter OLM plugin.

**Environment:**
- Flutter Version: 3.13.3
- Kotlin Gradle Plugin Version: 1.7.10
- Flutter OLM Plugin Version: 1.2.0
- Android Gradle Plugin Version: 7.3.0

**Additional Information:**
This version conflict prevents me from using both the Flutter OLM plugin and the latest Kotlin Gradle plugin simultaneously. It would be great if we could find a resolution or workaround to make these components compatible with each other.

Please let me know if there are any recommendations or if there's a plan to update the Flutter OLM plugin to support more recent Kotlin Gradle plugin versions.

Thank you for your assistance in resolving this issue.

**Comment by krille-chan** [comment]
Thanks for reporting. The kotlin gradle plugin has recently been updated to 1.5.20. Can you try again if this fixes your issue?

**Comment by krille-chan** [comment]
Kotlin has been updated so I'll close this now
