### ISSUE TITLE
Google Play complains about defective OpenSSL version

### ISSUE THREAD

**Issue by akvus** [famedly/matrix-dart-sdk#1561]
As per README, Matrix uses OpenSSL (libcrypto). When an application is published on Google Play, then at the 'production' page a warning is displayed:

```
Defective OpenSSL version
Your app uses a defective version of the OpenSSL library, which can cause your app to crash. Update to a fixed version of OpenSSL.

Defective versions:

OpenSSL 1.1.1g in lib/x86_64/libcrypto.so
```

The application is released with both:
```
 flutter_olm: ^1.2.0
  flutter_openssl_crypto: ^0.1.0
```
In `pubspec.yaml`.

How can a non defective version of OpenSSL be used instead?

**Comment by webzwo0i** [comment]
I stumbled across the same problem and needed to update flutter_openssl_crypto. Note that openssl 1.1.1 is EOL now, too: https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/

Probably only the last line is needed
```
diff --git a/android/build.gradle b/android/build.gradle
index 71cab22..c21eb90 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -25,13 +25,13 @@ apply plugin: 'com.android.library'
 apply plugin: 'kotlin-android'
 
 android {
-    compileSdkVersion 30
+    compileSdkVersion 33
 
     sourceSets {
         main.java.srcDirs += 'src/main/kotlin'
     }
     defaultConfig {
-        minSdkVersion 16
+        minSdkVersion 19
 
         externalNativeBuild {
             cmake {
@@ -53,5 +53,5 @@ android {
 
 dependencies {
     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
-    implementation "com.android.ndk.thirdparty:openssl:1.1.1g-alpha-1"
+    implementation "com.android.ndk.thirdparty:openssl:1.1.1l-beta-1"
 }
```

**Comment by krille-chan** [comment]
We should try out update flutter_openssl again and see if it fixes the problem without new sideeffects.

**Comment by krille-chan** [comment]
So to fix this bug we need to update the package https://github.com/famedly/flutter_openssl_crypto
There we have to update the gradle dependency and then try it out in Famedly and in FluffyChat (Android version, emulator and real device). Last time I tried this, the app crashed...

**Comment by krille-chan** [comment]
Update: Gedisa has said that they already tested it with this version:

```
implementation "com.android.ndk.thirdparty:openssl:1.1.1l-beta-1"
```

**Comment by coder-with-a-bushido** [comment]
@krille-chan `openssl:1.1.1l-beta-1` version has been tested with Famedly and Fluffychat on both emulator and device. The commit is merged to main, and it needs a release.

**Comment by krille-chan** [comment]
Done here: https://github.com/famedly/flutter_openssl_crypto/pull/2
once this is merged you may be able to publish by yourself by creating a (signed) tag `v0.2.0` but no idea if this works. Ping me if not :D
