### ISSUE TITLE
How camera access and usage is implemented for Android 

### ISSUE THREAD

**Issue by amirtaaghol** [famedly/matrix-dart-sdk#1604]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions

### Describe your problem

I need to know how the SDK gets camera (for video call explicitly) permission and uses what plugin to get video on an Android device.

### Describe your ideal solution

-

**Comment by krille-chan** [comment]
I'm sorry but that's a question not an issue. I would suggest to take a look into fluffychat code for example but we cannot give you support for free
