### ISSUE TITLE
Force close after logout and login again

### ISSUE THREAD

**Issue by darmawan01** [famedly/matrix-dart-sdk#1605]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [ ] I already asked for help in the chat

### In which Project did the bug appear?

Other

### On which platform did the bug appear?

Android, iOS

### SDK Version

  sdk: ">=2.19.2 <3.0.0"

  matrix: ^0.22.4
  flutter_olm: ^1.2.0
  flutter_openssl_crypto: ^0.1.0

```bash
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.4, on macOS 14.0 23A344 darwin-x64, locale en-ID)
    ! Upstream repository ssh://git@github.com/flutter/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to ssh://git@github.com/flutter/flutter.git to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.0)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Power’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

### Describe the problem caused by this bug

The apps is force close after logout and re-login again. looks like database cause this. Attached the screen shoot before apps is closed

### Screenshots or Logs

<img width="1139" alt="image" src="https://github.com/famedly/matrix-dart-sdk/assets/23370707/aa9ace54-1cfc-4c01-8f18-22fedd9f2488">

<img width="1448" alt="image" src="https://github.com/famedly/matrix-dart-sdk/assets/23370707/736b80c4-5154-4298-8cd5-71576368b5ff">

**Comment by krille-chan** [comment]
Please add some more information. Which version of the sdk are you using and which database backend is this? Please also provide a minimal program as code to reproduce it

**Comment by darmawan01** [comment]
I am using hive database.

```
 client = Client(
        'Test',
        databaseBuilder: (_) async {
          final dir = await getApplicationSupportDirectory();
          final db = HiveCollectionsDatabase('test', dir.path);
          await db.open();
          return db;
        },
        logLevel: kReleaseMode ? Level.warning : Level.verbose,
      );
      ```

**Comment by darmawan01** [comment]
fixed, issue is not from this sdk
