### ISSUE TITLE
Performance of isAttachmentInLocalStore

### ISSUE THREAD

**Issue by adrianvintu** [famedly/matrix-dart-sdk#1613]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [X] I already asked for help in the chat

### In which Project did the bug appear?

Famedly App

### On which platform did the bug appear?

Android

### SDK Version

matrix: ^0.22.7

### Describe the problem caused by this bug

I am using `if (await _event.isAttachmentInLocalStore(getThumbnail: true))` for each chat bubble, to show a download icon/button or not, in that chat bubble.

To my surprise, isAttachmentInLocalStore actually loads the file into memory `uint8list = await database.getFile(mxcUrl);` making the method similar to `downloadAndDecryptAttachment`.

The performance is terrible. 

For example, I have 10 chat bubbles which are all file attachments - one is 19 MB. I can easily see the flickering of the download icon appearing and disappearing because of `if (await _event.isAttachmentInLocalStore(getThumbnail: true))` which loads the whole file into memory.
Battery is also quickly drained.

1. Can you make the method `isAttachmentInLocalStore` return the correct result without loading the whole file into memory?

2.  Secondly, when I upload a file from the device and run `if (await _event.isAttachmentInLocalStore(getThumbnail: true))` I get... an exception: `"This event hasn't any attachment or thumbnail."`.
Why is the code breaking and not handling uploads elegantly and correctly?

**Comment by krille-chan** [comment]
Thanks for the issue. If you only want to know if an event has something you can download, I would more suggest to look at the event type. This can even be done synchroniously.

The method you have mentioned seems to be not correct. However as far as I can see it is not in use in the sdk, or fluffychat or famedly and I don't see the point keeping it at all. To know if the user can download something, we should look at the event type and to download we have a download method which also returns it from cache. I would suggest that we replace the method with a simple bool getter which leads to a database method `bool isFileCached(String mxcUrl)`.

**Comment by adrianvintu** [comment]
Than you for your feedbacki @krille-chan!

`If you only want to know if an event has something you can download`
->
I need to know it the file is cached or not, not if there is something we can downlod.

`I would suggest that we replace the method with a simple bool getter which leads to a database method bool isFileCached(String mxcUrl).`

This is kinda what I need! Something like `event.isFileCached(no params)`. Can you implement that?

**Comment by krille-chan** [comment]
> This is kinda what I need! Something like event.isFileCached(no params). Can you implement that?

Actually I would more suggest that you implement this in your own app. You probably have overwritten the Database like this is done in FluffyChat to provide features on the Flutter platform: https://github.com/krille-chan/fluffychat/blob/main/lib/utils/matrix_sdk_extensions/flutter_hive_collections_database.dart

Then you also have implemented your own way to get and store files. Just add another method to check if a file exists and you are done.

**Comment by krille-chan** [comment]
Even if you are using the new Matrix SDK Database which has some basic support for file storage, you can implement this by yourself by overwriting it in your app

**Comment by adrianvintu** [comment]
Thank you, I have extended DatabaseApi with `Future<bool> fileExists(Uri mxcUri) async`
