### ISSUE TITLE
New dart:io import breaks SDK compatibility with dart2js JIT compiler

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [famedly/matrix-dart-sdk#1621]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [X] I already asked for help in the chat

### In which Project did the bug appear?

Other

### On which platform did the bug appear?

Firefox

### SDK Version

b1b2b2ffe2bf49d7a0a09554bf866bd9ea6b47b1

### Describe the problem caused by this bug

Commit [b1b2b2f](https://github.com/famedly/matrix-dart-sdk/commit/b1b2b2ffe2bf49d7a0a09554bf866bd9ea6b47b1#r133430560) introduced more fine handling of network exceptions in the sync loop. Unfortunately, this dropped in `dart:io` as direct import into `client.dart`. The previous approach was not that fine graded, but imho way better than just silently dropping dart2js JIT support - at least as long as you have customers using it 😜.

### Steps To Reproduce

This issue is absolutely useless for external issue reporters btw.

### Screenshots or Logs

```
[WARNING] build_web_compilers:entrypoint on web/main.dart: Skipping compiling secure_messaging_app|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

matrix|lib/src/client.dart
```

**Comment by krille-chan** [comment]
Should be fixed now
