### ISSUE TITLE
building with flutter olm does not work

### ISSUE THREAD

**Issue by JenteJan** [famedly/matrix-dart-sdk#1686]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [ ] I already asked for help in the chat

### On which platform did the bug appear?

Android, iOS

### SDK Version

0.25.5

### Describe the problem caused by this bug

I cant build with flutter olm in my project, as this is the only way for encryption it essentially breaks the entire matrix package.

### Steps To Reproduce

1. create a new flutter project
2. flutter pub add matrix. flutter_olm, flutter_openssl_crypto, provider, path_provider
3. try building the app, which results in an error:

```
 Execution failed for task ':flutter_olm:buildCMakeDebug[arm64-v8a]'.
[        ] > com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/*/.pub-cache/hosted/pub.dev/flutter_olm-1.3.2/android/.cxx/Debug/h5m62296/arm64-v8a'
[        ]   [1/1] Linking CXX shared library libolm.so
[        ]   FAILED: libolm.so 
[        ]   : && /home/*/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21
--gcc-toolchain=/home/*/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/*/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections
-ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings
-Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libolm.so -o libolm.so CMakeFiles/olm.dir/src/account.cpp.o CMakeFiles/olm.dir/src/base64.cpp.o CMakeFiles/olm.dir/src/cipher.cpp.o CMakeFiles/olm.dir/src/crypto.cpp.o
CMakeFiles/olm.dir/src/memory.cpp.o CMakeFiles/olm.dir/src/message.cpp.o CMakeFiles/olm.dir/src/pickle.cpp.o CMakeFiles/olm.dir/src/ratchet.cpp.o CMakeFiles/olm.dir/src/session.cpp.o CMakeFiles/olm.dir/src/utility.cpp.o
CMakeFiles/olm.dir/src/pk.cpp.o CMakeFiles/olm.dir/src/sas.c.o CMakeFiles/olm.dir/src/ed25519.c.o CMakeFiles/olm.dir/src/error.c.o CMakeFiles/olm.dir/src/inbound_group_session.c.o CMakeFiles/olm.dir/src/megolm.c.o CMakeFiles/olm.dir/src/olm.cpp.o
CMakeFiles/olm.dir/src/outbound_group_session.c.o CMakeFiles/olm.dir/src/pickle_encoding.c.o CMakeFiles/olm.dir/lib/crypto-algorithms/aes.c.o CMakeFiles/olm.dir/lib/crypto-algorithms/sha256.c.o
CMakeFiles/olm.dir/lib/curve25519-donna/curve25519-donna.c.o  -latomic -lm && :
[   +1 ms]   ld: error: undefined symbol: std::ios_base::Init::Init()
[        ]   >>> referenced by iostream:74 (/snap/flutter/current/usr/include/c++/9/iostream:74)
[        ]   >>>               CMakeFiles/olm.dir/src/account.cpp.o:(__cxx_global_var_init)
[        ]   >>> referenced by iostream:74 (/snap/flutter/current/usr/include/c++/9/iostream:74)
[        ]   >>>               CMakeFiles/olm.dir/src/cipher.cpp.o:(__cxx_global_var_init)
[        ]   >>> referenced by iostream:74 (/snap/flutter/current/usr/include/c++/9/iostream:74)
[        ]   >>>               CMakeFiles/olm.dir/src/crypto.cpp.o:(__cxx_global_var_init)
[        ]   >>> referenced 6 more times
[        ]   ld: error: undefined symbol: std::ios_base::Init::~Init()
[        ]   >>> referenced by account.cpp:0 (/home/*/.pub-cache/hosted/pub.dev/flutter_olm-1.3.2/ios/src/account.cpp:0)
[        ]   >>>               CMakeFiles/olm.dir/src/account.cpp.o:(__cxx_global_var_init)
[        ]   >>> referenced by account.cpp:0 (/home/*/.pub-cache/hosted/pub.dev/flutter_olm-1.3.2/ios/src/account.cpp:0)
[        ]   >>>               CMakeFiles/olm.dir/src/account.cpp.o:(__cxx_global_var_init)
[        ]   >>> referenced by cipher.cpp:0 (/home/*/.pub-cache/hosted/pub.dev/flutter_olm-1.3.2/ios/src/cipher.cpp:0)
[        ]   >>>               CMakeFiles/olm.dir/src/cipher.cpp.o:(__cxx_global_var_init)
[        ]   >>> referenced 15 more times
[        ]   ld: error: undefined symbol: __assert_fail
[        ]   >>> referenced by base64.cpp:141 (/home/*/.pub-cache/hosted/pub.dev/flutter_olm-1.3.2/ios/src/base64.cpp:141)
[        ]   >>>               CMakeFiles/olm.dir/src/base64.cpp.o:(olm::decode_base64(unsigned char const*, unsigned long, unsigned char*))
[        ]   clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[        ]   ninja: build stopped: subcommand failed.
[        ]   C++ build system [build] failed while executing:
[        ]       /home/*/Android/Sdk/cmake/3.18.1/bin/ninja \
[        ]         -C \
[        ]         /home/*/.pub-cache/hosted/pub.dev/flutter_olm-1.3.2/android/.cxx/Debug/h5m62296/arm64-v8a \
[        ]         olm
[        ]     from /home/*/.pub-cache/hosted/pub.dev/flutter_olm-1.3.2/android
```

Im running on:

Flutter SDK 3.16.1
Dart 3.2.1
Kotlin Gradle 1.7.10 (have tried changing to 1.5.20 but was not sure if that worked when i changed it in the build.gradle as it seemed to result in a version mismatch error)
matrix sdk 0.25.5
flutter_olm 1.3.2 (have also tried 1.40 and 1.4.1 both resulted in an error)

Thanks for any answers in advance

**Comment by JenteJan** [comment]
@krille-chan That doesn't seem to change anything, eventhough Im still not sure changing the value of kotlin version in build.gradle alone is doing anything. I was thinking the problem may be due to not having libolm installed on my linux device. I looked at the dart olm package which did have some instructions Im not sure i should follow. When trying however I failed to find the script they were talking about and only managed to run ```sudo apt install libolm3```

**Comment by JenteJan** [comment]
@krille-chan the problem only occurs on android, I tested on a mac and it worked only for ios

**Comment by JenteJan** [comment]
Okay for anybody struggling with this problem, the docs seem to be missing some information for people who's packages don't automatically build, In the end I'm not sure what actually fixed the problem but for 
flutter_olm: check out this github: https://github.com/famedly/olm that contains documentation the pub dev page is missing. run the build scripts on linux from inside the folder where the package lives ("home/user/.pub-cache/hosted/flutter_olm")

add these lines to your build.gradle in your flutter project:
```
android { 
  defaultConfig{
    ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
    }
    packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
    }
}
```

running flutter clean or deleting the package folder then trying again to build might also result in a succes.

**Comment by JenteJan** [comment]
@krille-chan I am currently working on a matrix and flutter based chat app, and I was wondering if there was some way we could have a chat about it. seeing as you seem to be the person that knows most about the possibilities and limitations of working with matrix in flutter. I couldn't find another way to message you which is why I did so using this comment. You can reply directly or through: flipchat.messenger ( at ) gmail ( dot ) com

**Comment by krille-chan** [comment]
Thank you so much. So it looks like this is a issue of missing documentation. We will take a look. @JenteJan we will contact you :-) very looking forward what you build with the SDK

**Comment by JenteJan** [comment]
> Thank you so much. So it looks like this is a issue of missing documentation. We will take a look. @JenteJan we will contact you :-) very looking forward what you build with the SDK

yes thanks for the reply, i forgot to mention this in my other comments but one of the reasons it worked for me in the end may have been running ./gradlew build inside the folder of flutter_olm.
