### ISSUE TITLE
Periodical sync errors on web

### ISSUE THREAD

**Issue by abigotado** [famedly/matrix-dart-sdk#1692]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [ ] I already asked for help in the chat

### In which Project did the bug appear?

Other

### If you selected \"Other\" as Project, please enter in which project the bug occurred.

matrix_dart_sdk

### On which platform did the bug appear?

Chrome

### SDK Version

latest

### Describe the problem caused by this bug

After successfully connecting to matrix server I'm periodically getting `Error during processing events`. As far as I understand these errors are come from these events (on mobile platform everything is okay):
```
flutter: [Matrix] \^[[34mBenchmark: Process sync -> 3 ms (1 items, 3.0 ms/item)<…>
flutter: [Matrix] \^[[34mBenchmark: Process sync -> 0 ms (0 items, 0 ms/item)<…>
flutter: [Matrix] \^[[34mBenchmark: Process sync -> 1 ms (0 items, 1 ms/item)<…>
flutter: [Matrix] \^[[34mBenchmark: Process sync -> 7 ms (1 items, 7.0 ms/item)<…>
```

### Steps To Reproduce

Here is my matrix client:
```dart
@module
abstract class ApiModule {
  /// Matrix client.
  @preResolve
  Future<Client> createMatrixClient() async {
    final Client client = Client(
      'SquadderChat',
      // ignore: prefer_final_parameters
      databaseBuilder: kIsWeb
          ? (final Client client) async {
              final MatrixSdkDatabase database =
                  MatrixSdkDatabase(client.clientName);
              await database.open();
              return database;
            }
          : FlutterHiveCollectionsDatabase.databaseBuilder,
      logLevel: kDebugMode ? Level.verbose : Level.error,
      nativeImplementations: kIsWeb
          ? NativeImplementationsWebWorker(Uri.parse('/'))
          : NativeImplementationsIsolate(compute),
    );
    return client;
  }
}
```

### Screenshots or Logs

Here are errors on Web:
```
[Matrix] Error during processing events - TimeoutException after 0:00:40.000000: Future not completed
[Matrix] Error during processing events - TimeoutException after 0:00:40.000000: Future not completed
[Matrix] Error during processing events - TimeoutException after 0:00:40.000000: Future not completed


### Security related

_No response_

**Comment by krille-chan** [comment]
I don't see a problem here. The logs are already saying that there is a TimeoutException after 40 seconds which means the server is not responding. What would you the sdk expect to do instead?

**Comment by abigotado** [comment]
@krille-chan  The strange thing is that it always happens on web. I haven't seen it was successfull. But if I start mobile app at the same time on the same device - all these requests are successful. If server was not responding there would be errors on both platforms, I think. It seems to be connected to the platform.

**Comment by krille-chan** [comment]
Can you reproduce it with any server? Have you tried different also like public ones like matrix.org?

**Comment by abigotado** [comment]
@krille-chan Have tried with matrix.org, but it doesn't generate sync requests at all. Isn't it associated with database? 'Cause this sync requests are from here (it's `client.dart` file): 

```dart
      final database = this.database;
      if (database != null) {
        await userDeviceKeysLoading;
        await roomsLoading;
        await _accountDataLoading;
        _currentTransaction = database.transaction(() async {
          await _handleSync(syncResp, direction: Direction.f);
          if (prevBatch != syncResp.nextBatch) {
            await database.storePrevBatch(syncResp.nextBatch);
          }
        });
        await runBenchmarked(
          'Process sync',
          () async => await _currentTransaction,
          syncResp.itemCount,
        );
      } else {
        await _handleSync(syncResp, direction: Direction.f);
      }
```

**Comment by krille-chan** [comment]
> Have tried with matrix.org, but it doesn't generate sync requests at all.

That would mean the app could not work with matrix.org but there are thousands of users using this server with this sdk 🤔

> Isn't it associated with database?
The timeout error comes from this line in `client.dart` line 1747:

```dart
      final syncResp = await syncRequest.timeout(responseTimeout);
```

So this is just related to the server not responding and nothing else.

**Comment by abigotado** [comment]
> That would mean the app could not work with matrix.org but there are thousands of users using this server with this sdk 🤔
Well, it works perfectly with matrix.org server - connects, sends messages, but doesn't generate sync logs at all. Dunno the reason.

> So this is just related to the server not responding and nothing else.

Got it, but still can't understand how can the same server respond to mobile app and not respond to the web app at the very same moment.

**Comment by krille-chan** [comment]
I think this has been fixed now. Haven't seen this in a while. Please ping me and reopen if this happens again :)
