### ISSUE TITLE
Error in Matrix logs on startup

### ISSUE THREAD

**Issue by cofirazak** [famedly/matrix-dart-sdk#1751]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [ ] I already asked for help in the chat

### In which Project did the bug appear?

Other

### If you selected \"Other\" as Project, please enter in which project the bug occurred.

famedly/matrix-dart-sdk

### On which platform did the bug appear?

iOS

### SDK Version

0.26.1

### Describe the problem caused by this bug

On startup method PushruleEvaluator.fromRuleset(PushRuleSet ruleset) – receives PushRuleSet including unknown for matrix-dart-sdk 0.26.1 conditions of kind **event_property_contains** and **event_property_is**.

**(app keeps working with this)**

As the result we see this in logs:

<img width="1274" alt="Снимок экрана 2024-03-26 в 21 52 36" src="https://github.com/famedly/matrix-dart-sdk/assets/2613578/b5928497-05c3-4001-ac47-0d8efa7480c4">

<img width="1375" alt="Снимок экрана 2024-03-26 в 21 05 55" src="https://github.com/famedly/matrix-dart-sdk/assets/2613578/ce175ce4-df42-4a2e-8c0d-bce18acfd659">

### Steps To Reproduce

Run on Android or iOS a project using matrix-dart-sdk version 0.26.1

### Screenshots or Logs

<img width="1440" alt="Снимок экрана 2024-03-26 в 20 52 49" src="https://github.com/famedly/matrix-dart-sdk/assets/2613578/ff5f0729-f10a-41b2-b4ca-71695d73785c">

<img width="1440" alt="Снимок экрана 2024-03-26 в 20 54 30" src="https://github.com/famedly/matrix-dart-sdk/assets/2613578/49a6e536-45bc-4438-8e17-4e48bbd942a3">

**Comment by krille-chan** [comment]
Thanks for opening the issue. We will take a look on it :)

**Comment by krille-chan** [comment]
Duplication of https://github.com/famedly/product-management/issues/1539
