### ISSUE TITLE
users somehow get an old version of powerlevels state

### ISSUE THREAD

**Issue by td-famedly** [famedly/matrix-dart-sdk#1830]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [X] I already asked for help in the chat

### In which Project did the bug appear?

Famedly App

### On which platform did the bug appear?

Chrome

### SDK Version

v0.29.8

### Describe the problem caused by this bug

1 user has been randomly getting an older version of the powerlevels event. This automatically gets fixed after a clear cache or a refresh. This also happens after a postLoad. 

### Steps To Reproduce

no clue

### Screenshots or Logs

![image](https://github.com/famedly/matrix-dart-sdk/assets/152161658/f42dcd6b-b5cf-4f47-acdd-58ebbfcdcb21)

was an admin and had famedly calls enabled but got a old pl state

**Comment by nikzen** [comment]
We also saw this behavior:

### Initial State

<img width="270" alt="image" src="https://github.com/famedly/matrix-dart-sdk/assets/33399346/ef9f5965-ddd9-4b6b-b18d-5e2c4ca7cfea">

### Delete Cache & Refresh Page 

<img width="361" alt="image" src="https://github.com/famedly/matrix-dart-sdk/assets/33399346/12175db2-c4c6-4d21-94a9-a26a0ca3db06">

After deleting cache & refresh page it worked

**Comment by nico-famedly** [comment]
This should be fixed in 0.29.10, please reopen, if you can still reproduce it with that.
