### ISSUE TITLE
#47 ⁃ Imp: Famedly: otk upload aftermath

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#184]
In GitLab by @Sorunome on Aug 2, 2021, 21:09

#### Description
https://gitlab.com/famedly/company/frontend/famedlysdk/-/merge_requests/753 aftermath

client.handleSync --> client.fakeSync & deprecate old one   
client.\_handleSync --> client.\_handleSync   
deprecate room.\_handleFakeSync

also `sync.deviceOneTimeKeysCount ??= {'signed_curve25519': 100};` should not hardcode the `100` but instead use libolm, with fallback to 100 if libolm is unavailable

### Importance for the User

In the best case the user doesn't notice this ever. In the worst case this causes e2ee bugs or security issues or long wait times for bug fixes.

### User Case
Please at a specific Use Case for this feature in the format of a User Story:   **As a** — Patient   **I want** — to have a new online payment feature implemented into the Instant Messaging app   **So that** — I can pay my medicines and doctor fees through the app.

This doesn't provide immediate value to the user, it just improves the existing code in the app, so that there will be less bugs in the future.

### Feature Usage Metrics
 

- - -
### Checklist DoR
* [x] The issue title and description should be explained in English language.
* [ ] Business value is clear and understood.
* [x] Every attached media (if applicable) should include a short description.
* [x] The feature title and description should be explained in English language.
* [x] Engineer has confirmed this feature is technically feasible.

**Comment by krille-chan** [comment]
Fixed now :)
