### ISSUE TITLE
auto clearCache when needed (on broken state)

### ISSUE THREAD

**Issue by td-famedly** [famedly/matrix-dart-sdk#1873]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions

### Describe your problem

We sometimes have bugs in the SDK which break the database, f.ex we recently had a bug where we would apply older state events (fixed by https://github.com/famedly/matrix-dart-sdk/pull/1846). Unless you clearCache, users are going to keep facing those bugs.

### Describe your ideal solution

When we fix such a bug, the SDK should automatically clear the cache on first startup.

**Comment by herr-rodrigo** [comment]
this is actually already in place by updating the version of the DB.

**Comment by td-famedly** [comment]
just bump the database version which should do it
