### ISSUE TITLE
Not able to run the project in local  dartMatrixSdk

### ISSUE THREAD

**Issue by gyanupadhyay** [famedly/matrix-dart-sdk#1898]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [ ] I already asked for help in the chat

### In which Project did the bug appear?

Other

### If you selected \"Other\" as Project, please enter in which project the bug occurred.

dart Matrix Sdk

### On which platform did the bug appear?

Android

### Describe the problem caused by this bug

Not able to run the project this the problem it is causing.

### Steps To Reproduce

1. Clone the dartMatrixSdk repo.
2. Open in Vscode
3. Now try to run the main.dart file it open the the launch.json but the project will not run and also getting the following errror in the console attached in the screenshot below.
![Screenshot (711)](https://github.com/user-attachments/assets/a2fdb86d-debd-428e-a28f-f4c8ff1cf897) 

![Screenshot (710)](https://github.com/user-attachments/assets/d346bc72-94a3-46c5-8daa-fd1dcd4e2c17)

**Comment by krille-chan** [comment]
Closed as this is a support request and not an issue or a bug

**Comment by gyanupadhyay** [comment]
Can I get any help on this issue to resolve this my side?
