### ISSUE TITLE
`PushNotification`'s `devices` field is not compatible with Sygnal

### ISSUE THREAD

**Issue by vanyasem** [famedly/matrix-dart-sdk#1947]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [ ] I already asked for help in the chat

### In which Project did the bug appear?

`matrix-dart-sdk`

### On which platform did the bug appear?

Android, iOS

### SDK Version

0.34.0

### Describe the problem caused by this bug

`PushNotification` object in `martix-dart-sdk` is not compatible with the reference implementation of a Push Gateway for Matrix called Sygnal

The `PushNotification` object in the SDK has a mandatory `devices` field: https://github.com/famedly/matrix-dart-sdk/blob/v0.34.0/lib/src/utils/push_notification.dart#L20 which is not sent by Sygnal

I have only tested the GCM (FCM) implementation of Sygnal, but by reading the [appropriate source code](https://github.com/matrix-org/sygnal/blob/v0.15.1/sygnal/apnspushkin.py), I can confirm that this issue affects APN notifications as well

See https://github.com/matrix-org/sygnal/pull/319 for comments of the maintainer of Sygnal

As far as I could tell, despite being required, it's not used by the SDK in any capacity

I believe the confusion happened because of the following text in the matrix push gateway API spec: https://spec.matrix.org/v1.12/push-gateway-api/
<img width="624" src="https://github.com/user-attachments/assets/d73fde4b-0796-46c2-83c8-8be25376d43d">

This field is only marked as required for server-side endpoints of the push gateway, and should not be required on the client-side

I made a PR that makes the `devices` field optional: https://github.com/famedly/matrix-dart-sdk/pull/1949

**Comment by vanyasem** [comment]
You can send a fake test notification to a device with `curl`: https://github.com/matrix-org/sygnal/blob/v0.15.1/docs/troubleshooting.md#sending-a-notification-to-sygnal-manually-with-curl

Sending the following notification body:
```json
{
  "notification": {
    "event_id": "\$3957tyerfgewrf384",
    "room_id": "!slw48wfj34rtnrf:example.org",
    "type": "m.room.message",
    "sender": "@exampleuser:example.org",
    "sender_display_name": "Major Tom",
    "room_name": "Mission Control",
    "room_alias": "#exampleroom:example.org",
    "prio": "high",
    "content": {
      "msgtype": "m.text",
      "body": "I'm floating in a most peculiar way."
    },
    "counts": {
      "unread": 2,
      "missed_calls": 1
    },
    "devices": [
      {
        "app_id": "<APP ID HERE>",
        "pushkey": "<PUSHKEY HERE>",
        "pushkey_ts": 12345678,
        "data": {},
        "tweaks": {
          "sound": "bing"
        }
      }
    ]
  }
}
```

results in the following message being transmitted to FCM:
```json
{
  "sender_display_name": "Major Tom",
  "room_name": "Mission Control",
  "sender": "@exampleuser:example.org",
  "unread": 2,
  "missed_calls": 1,
  "prio": "high",
  "type": "m.room.message",
  "event_id": "",
  "content_body": "I'm floating in a most peculiar way.",
  "room_alias": "#exampleroom:example.org",
  "room_id": "!slw48wfj34rtnrf:example.org",
  "content_msgtype": "m.text"
}
```

This logic is defined here: https://github.com/matrix-org/sygnal/blob/v0.15.1/sygnal/gcmpushkin.py

**Comment by vanyasem** [comment]
An example of an `event_id_only` push message:

```json
{
  "unread": "1",
  "missed_calls": null,
  "prio": "high",
  "event_id": "$3957tyerfgewrf384",
  "room_id": "!slw48wfj34rtnrf:example.org"
}
```

**Comment by krille-chan** [comment]
Same with #1948

**Comment by vanyasem** [comment]
@krille-chan the documentation that you linked specifies the JSON model for *the API endpoint* `/_matrix/push/v1/notify`, for which the `devices` field is indeed mandatory

You misunderstood the meaning of the model linked above. It's **a server-side model** for the Push Gateway itself. It's not meant to be sent back to users devices

`sygnal` is a **reference** Push Gateway by the Matrix Foundation

The definition of "reference" is:

> A software example of a specification, intended to help others implement their own version of the specification or find problems during the creation of a specification.

You can learn more about the meaning of a "reference implementation" here: https://en.wikipedia.org/wiki/Reference_implementation

Arguing that an official reference implementation is somehow wrong, and your specific interpretation of the documentation is really bold.

Just to be sure, the field in question has been discussed directly with the Matrix team, and they confirmed that `devices` is only mandatory on the server-side, and that it makes no sense to include it in the model when sending a notification back to the device. See https://github.com/matrix-org/sygnal/pull/319 for more details

Your implementation is the only one that does that, yet you still choose to stand by your incorrect interpretation of the docs.

**Comment by vanyasem** [comment]
Btw the correct documentation to link would be https://github.com/matrix-org/sygnal/blob/main/docs/applications.md#firebase-cloud-messaging, which specifies the client-side model for the push:

```json
{
  "event_id": "$3957tyerfgewrf384",
  "type": "m.room.message",
  "sender": "@exampleuser:example.org",
  "room_name": "Mission Control",
  "room_alias": "#exampleroom:example.org",
  "sender_display_name": "Major Tom",
  "content_msgtype": "m.text",
  "content_body": "I'm floating in a most peculiar way.",
  "room_id": "!slw48wfj34rtnrf:example.org",
  "prio": "high",
  "unread": "2",
  "missed_calls": "1"
}
```
