### ISSUE TITLE
`PushNotification`'s `counts` field is not compatible with Sygnal

### ISSUE THREAD

**Issue by vanyasem** [famedly/matrix-dart-sdk#1948]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [ ] I already asked for help in the chat

### In which Project did the bug appear?

`matrix-dart-sdk`

### On which platform did the bug appear?

Android, iOS

### SDK Version

0.34.0

### Describe the problem caused by this bug

`PushNotification` object in `martix-dart-sdk` is not compatible with the reference implementation of a Push Gateway for Matrix called Sygnal

The `PushNotification` object in the SDK has a separate `counts` field that holds a `PushNotificationCounts` object containing `unread` and `missed_calls` fields.

However, Sygnal sends `unread` and `missed_calls` fields at the root of the model, which means that they are not recognized by `martix-dart-sdk`:

An example of an `event_id_only` push FCM message sent from Sygnal:
```json
{
  "unread": "1",
  "missed_calls": null,
  "prio": "high",
  "event_id": "$3957tyerfgewrf384",
  "room_id": "!slw48wfj34rtnrf:example.org"
}
```

I have only tested the GCM (FCM) implementation of Sygnal, but by reading the [appropriate source code](https://github.com/matrix-org/sygnal/blob/v0.15.1/sygnal/apnspushkin.py), I can confirm that this issue affects APN notifications as well

Related to https://github.com/famedly/matrix-dart-sdk/issues/1947

**Comment by vanyasem** [comment]
You can send a fake test notification to a device with `curl`: https://github.com/matrix-org/sygnal/blob/v0.15.1/docs/troubleshooting.md#sending-a-notification-to-sygnal-manually-with-curl

Sending the following notification body:
```json
{
  "notification": {
    "event_id": "$3957tyerfgewrf384",
    "room_id": "!slw48wfj34rtnrf:example.org",
    "type": "m.room.message",
    "sender": "@exampleuser:example.org",
    "sender_display_name": "Major Tom",
    "room_name": "Mission Control",
    "room_alias": "#exampleroom:example.org",
    "prio": "high",
    "content": {
      "msgtype": "m.text",
      "body": "I'm floating in a most peculiar way."
    },
    "counts": {
      "unread": 2,
      "missed_calls": 1
    },
    "devices": [
      {
        "app_id": "<APP ID HERE>",
        "pushkey": "<PUSHKEY HERE>",
        "pushkey_ts": 12345678,
        "data": {},
        "tweaks": {
          "sound": "bing"
        }
      }
    ]
  }
}
```

Results in the following message being transmitted to FCM by Sygnal:
```json
{
  "sender_display_name": "Major Tom",
  "room_name": "Mission Control",
  "sender": "@exampleuser:example.org",
  "unread": "2",
  "missed_calls": "1",
  "prio": "high",
  "type": "m.room.message",
  "event_id": "$3957tyerfgewrf384",
  "content_body": "I'm floating in a most peculiar way.",
  "room_alias": "#exampleroom:example.org",
  "room_id": "!slw48wfj34rtnrf:example.org",
  "content_msgtype": "m.text"
}
```

This logic is defined here: https://github.com/matrix-org/sygnal/blob/v0.15.1/sygnal/gcmpushkin.py

**Comment by krille-chan** [comment]
Well Sygnal is then sending a different model which is not part of the spec. You have to bring your own data model then. The correct model is described here: https://spec.matrix.org/v1.12/push-gateway-api/#post_matrixpushv1notify and the matrix dart sdk is parsing it correctly.

**Comment by nico-famedly** [comment]
The counts field isn't required in the link above, is it?

**Comment by vanyasem** [comment]
See my reply in #1947 and #1949 : https://github.com/famedly/matrix-dart-sdk/issues/1947#issuecomment-2468662803, https://github.com/famedly/matrix-dart-sdk/pull/1949#issuecomment-2468662391
