### ISSUE TITLE
Error parsing push rule Instance of 'PushRule' during Fluffy Chat init

### ISSUE THREAD

**Issue by uz960646063** [famedly/matrix-dart-sdk#1964]
### Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions.
- [x] I already asked for help in the chat

### In which Project did the bug appear?

Other

### If you selected \"Other\" as Project, please enter in which project the bug occurred.

FluffyChat

### On which platform did the bug appear?

Android

### SDK Version

0.34.0

### Describe the problem caused by this bug

I want to build my own Matrix client based on FluffyChat. My homeserver uses the Sygnal GCM push gateway. After logging into the server, the application logs show the following errors:

```
I/flutter (31794): [Matrix] Error parsing push rule Instance of 'PushRule' - Exception: Unknown push condition: event_property_contains
I/flutter (31794): [Matrix] Error parsing push rule Instance of 'PushRule' - Exception: Unknown push condition: event_property_is
I/flutter (31794): [Matrix] Error parsing push rule Instance of 'PushRule' - Exception: Unknown push condition: event_property_is
```

I am unable to receive notifications even though the pusher is registered, and there are no errors on the Sygnal side.

### Screenshots or Logs

```
I/flutter (31794): [Matrix] Error parsing push rule Instance of 'PushRule' - Exception: Unknown push condition: event_property_contains
I/flutter (31794): [Matrix] Error parsing push rule Instance of 'PushRule' - Exception: Unknown push condition: event_property_is
I/flutter (31794): [Matrix] Error parsing push rule Instance of 'PushRule' - Exception: Unknown push condition: event_property_is
```

**Comment by krille-chan** [comment]
For reference. The push rules are described here: https://spec.matrix.org/v1.12/client-server-api/#conditions-1
The implementation in the SDK can be found here: https://github.com/famedly/matrix-dart-sdk/blob/main/lib/src/utils/pushrule_evaluator.dart#L190 looks like the implementation of `event_property_contains` and `event_property_is` is missing
