### ISSUE TITLE
#55 ⁃ Feat: External: HTTP/SOCKS5 proxy support

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#221]
In GitLab by @alandiwix on Oct 1, 2021, 12:50

Would be nice to have. Does the SDK abstract all http transport through some class? Maybe https://gitlab.com/famedly/company/frontend/famedlysdk/-/blob/main/lib/src/utils/http_timeout.dart that is?

* [x] The issue title and description should be explained in English language.
* [ ] Feature request is provided in story template: 
* [ ] Business value is clear and understood.
* [x] Every attached media (if applicable) should include a short description.
* [ ] Engineer has confirmed this feature is technically feasible.

**Comment by krille-chan** [comment]
Closed because of inactivity
