### ISSUE TITLE
#56 ⁃ Imp: Famedly: Improve exceptions handling

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#224]
In GitLab by @krille-chan on Oct 11, 2021, 13:04

### Release notes / Short description
Throw exceptions if something is wrong and handle them in higher level (In the SDK are a lot of parts where exceptions are just caught and then ignored)

#### User story
   **As a**

* Patient   
    
**I want**
* to have a new online payment feature implemented into the Instant Messaging app   
    
**So that**
* I can pay my medicines and doctor fees through the app.   
    
### Importance for the user

- - -
### DoR checklist

* [x] The issue title and description should be explained in English language.
* [x] Feature request is provided in story template:
* [ ] Business value is clear and understood.
* [x] Every attached media (if applicable) should include a short description.
* [x] Engineer has confirmed this feature is technically feasible.

**Comment by krille-chan** [comment]
The issue is not clear enough anymore and probably outdated. If we find places where we could improve the situation we should do it or collect them in a new issue
