### ISSUE TITLE
#57 ⁃ Imp: Famedly: Make Matrix Identifiers, deviceIDs their own types

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#225]
In GitLab by @krille-chan on Oct 11, 2021, 13:25

#### User story
   **As a**

* Patient

**I want**

* to have a new online payment feature implemented into the Instant Messaging app

**So that**

* I can pay my medicines and doctor fees through the app.

### Importance for the user

- - -
### DoR checklist

* [x] The issue title and description should be explained in English language.
* [x] Feature request is provided in story template:
* [ ] Business value is clear and understood.
* [x] Every attached media (if applicable) should include a short description.
* [x] Engineer has confirmed this feature is technically feasible.

**Comment by krille-chan** [comment]
Duplication of https://github.com/famedly/product-management/issues/65
