### ISSUE TITLE
#62 ⁃ Imp: Famedly: Use an optional parameter for initializing the encryption code instead of a nullable one

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#236]
In GitLab by @nico-famedly on Oct 28, 2021, 13:36

### Detailed description
The following discussion from !867 should be addressed:

* [ ] @krille-chan started a [discussion](https://gitlab.com/famedly/company/frontend/famedlysdk/-/merge_requests/867#note_717179492):  (+1 comment)

    > What about we make the parameter optional here:
    > ```dart
    > Future<void> init([String? cachedOlmAccount]) async {
    > ```
    > This could be more intuitive#### User story   **As a**

* Patient

**I want**

* to have a new online payment feature implemented into the Instant Messaging app

**So that**

* I can pay my medicines and doctor fees through the app.

### Importance for the user

- - -
### DoR checklist

* [x] The issue title and description should be explained in English language.
* [x] Feature request is provided in story template:
* [ ] Business value is clear and understood.
* [x] Every attached media (if applicable) should include a short description.
* [x] Engineer has confirmed this feature is technically feasible.

**Comment by krille-chan** [comment]
The code line seems to no longer exist so I close this
