### ISSUE TITLE
#88 ⁃ Deleted message still displayed by `room.lastEvent`

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#299]
In GitLab by @h.carnot on May 27, 2022, 10:13

Current behavior: If a user deletes a message in a chat room the preview of the roomlist is not properly updating. This effects end user and possibly leaks information that should have been deleted.

Expected behavior:  The preview of the roomlist updates properly when a message is deleted by a user.

Happens in WebApp and mobileApp.

# DoR Bug report
* [x] The issue title and description should be explained in English language.
* [x] Description of current and expected behavior is understood.
* [x] If necessary,  reproduction steps should be included.
* [x] Every attached media (if applicable) includes a short description.
* [x] Bug can be reproduced in the latest development version
* [x] Severity is understood.
* [x] Responsible squad has been identified (issue is labeled)
* [x] There is a list of affected components if needed.
* [x] There is an estimate on the effort to fix the bug.

**Comment by Mar-Ga** [comment]
it is fixed so we can close it
