### ISSUE TITLE
#89 ⁃ Feat: Famedly: Introduce case-specific Client.compute methods

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#302]
In GitLab by @ghost on Jun 15, 2022, 08:05

As in https://gitlab.com/famedly/company/frontend/famedly-web/-/merge_requests/455 or https://gitlab.com/famedly/company/frontend/libraries/flutter_matrix_html/-/blob/master/lib/code_block.dart#L155, we make use of Flutter's isolate support.

As it is technically not possible to implement [`Isolates`](https://api.dart.dev/stable/2.17.3/dart-isolate/Isolate-class.html) in web, I'd like to propose a case-specific architecture of those threaded implementations: Instead of one general [`Client.compute`](https://pub.dev/documentation/matrix/latest/matrix/Client/compute.html) method, we should have dedicated methods for each threaded call we actually do. This way, they could easily be implemented in Web using a [Webworker](https://api.dart.dev/stable/2.17.3/dart-html/WorkerGlobalScope-class.html).

I'd propose to deprecate `Client.compute` in favor of an optional property `Client.executors` having properties similar to this:

```dart

abstract class MatrixThreadedExecutions {

FutureOr<Uint8List> resizeImage(Uint8List bytes, int height, int width);

FutureOr<Uint8List> generateUploadKey();

...

}

```

* [x] The issue title and description should be explained in English language.
* [ ] Feature request is provided in story template: 
* [ ] Business value is clear and understood.
* [x] Every attached media (if applicable) should include a short description.
* [ ] Engineer has confirmed this feature is technically feasible.

**Comment by krille-chan** [comment]
Has been implemented
