### ISSUE TITLE
Imp: Famedly #75 ⁃ Change the way how last event of a room is stored

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#360]
### Category/ Services
- Matrix Dart SDK

### Detailed description
 
We should change the way how the last event of a room gets stored. It should not be stored in the room anymore but the event ID to the corresponding event should be stored.

### Steps to implement this:
- [x] Room object should contain a member `Event? lastEvent`
- [x] Room.toJson() and Room.fromJson(json) should import/export the whole event
- [ ] in the Sync logic the last event should be updated for any existing room in client.rooms
- [ ] in `Database.storeRoomUpdate()` for joined rooms the lastEvent should be updated

**Comment by krille-chan** [comment]
I've put this in refinement so that we can talk about it again. We should tackle this soon to fix several bugs

**Comment by herr-rodrigo** [comment]
Reviewed on refinement meeting with the IM team. 
Everything is clear to start to work on this.
